package exceptions

import "testing"

func TestExceptions(t *testing.T) {
	// Stub
}
